version: "3.7"
services:

    jq:
      image: imega/jq:1.6
      env_file: .env
      volumes:
        - .:/opt/app
      working_dir: /opt/app

    terraform:
      image: hashicorp/terraform:0.14.5
      env_file: .env
      volumes:
        - .:/opt/app
      working_dir: /opt/app

    aws:
      image: mesosphere/aws-cli
      env_file: .env
      volumes:
        - .:/opt/app
      working_dir: /opt/app

