version: "3.8"
services:
    3m:
      image: runner
      build:
        context: .
        dockerfile: ./docker/Dockerfile.3m
      # env_file: .env
      volumes:
        - .:/3m
      working_dir: /3m